name: zuvirocl_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.4
  google_fonts: ^8.0.1
  flutter_svg: ^2.0.10
  logger: any
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  permission_handler: ^11.0.1
  diacritic: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mapa_demo_actualizado.svg
    - assets/avatar_default.png